# Site settings
title:
email: jonathan.tapia@magmalabs.io
description: ''
baseurl: ''
url: http://jtapia.github.io
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
github_username:  jtapia

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: default
search: true

# Build settings
plugins:
  - jekyll-feed
  - jekyll-haml
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

# Reading Files
include:
  - _pages
  - _layouts

author:
  name: 'Jonathan Tapia'
  avatar: '/assets/images/bio-photo.jpg'
  bio: 'Web developer'
  links:
    - label: 'GitHub'
      icon: 'fab fa-fw fa-github'
      url: 'https://github.com/jtapia'

footer:
  links:
    - label: 'GitHub'
      icon: 'fab fa-fw fa-github'
      url: 'https://github.com/jtapia'

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true

# category_archive:
#   type: liquid
#   path: /categories/

# tag_archive:
#   type: liquid
#   path: /tags/

github: [metadata] #encoding: UTF-8 kramdown: input: GFM hard_wrap: false
